model_id: llava-hf/llava-1.5-7b-hf
batch_size: 10
max_length: 512
start_index: 0
num_batches: 100
coco_root: /path/to/coco2017   # contains val2017/ and annotations/
outdir: ./outputs
quant_4bit: true
dtype: float16
